# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.destination import Destination  # noqa: E501
from openapi_client.rest import ApiException


class TestDestination(unittest.TestCase):
    """Destination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestination(self):
        """Test Destination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.destination.Destination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
