# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.destination_types_api import DestinationTypesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDestinationTypesApi(unittest.TestCase):
    """DestinationTypesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.destination_types_api.DestinationTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_get_destination_types(self):
        """Test case for api_get_destination_types

        Retrieves general information about the configuration required for all supported destination types.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
