# coding: utf-8

"""
    Stitch Connect

    https://www.stitchdata.com/docs/developers/stitch-connect/api  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.error_object_error import ErrorObjectError  # noqa: E501
from openapi_client.rest import ApiException


class TestErrorObjectError(unittest.TestCase):
    """ErrorObjectError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorObjectError(self):
        """Test ErrorObjectError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.error_object_error.ErrorObjectError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
